Added robots command to manage robots
tu-darmstadt-ros-pkg/tuda_workspace_scripts pull request #3
Opened 2024-11-25 10:28 UTC by StefanFabian

First implementation of robots command loading commands from yaml and launching them in tmux panes or windows.

Examples:
`tuda_wss robots hans all reboot` Would reboot all computers belonging to the robot *hans*.
`tuda_wss robots gretel gretel-main ssh` Would ssh into the *gretel-main* PC of the *gretel* robot.

A config would look as follows:
```
commands: # shared commands for all pcs
  hello: "echo Hello world"
remote_pcs:
  athena-main:
    user: hector
    commands:
      reboot: ~ # Disables the default reboot command for this pc
  athena-jetson:
    user: hector
    commands:
      restart_docker: "sudo systemctl restart docker"
```

Per default the commands `ssh`, `reboot`, `shutdown` and `ssh-copy-id` are available for all robots.
These commands can simply be overridden by specifying the command name key and a new command for a robot or remote pc.
To disable a default command or shared command, you can use the command name and set its value to `~` (None).

You can also specify multiple robots in a single yaml by having the name of the robot as the root keys (none of them can be named `remote_pcs` though :wink:)

Configs are loaded from directories and files specified in the environment variable `TUDA_WSS_ROBOTS`.

2024-11-27 08:36 UTC, StefanFabian commented on tuda_workspace_scripts/tmux.py
> +        window.name = list(commands.keys())[0] if commands is dict else commands[0]
Good catch! But window_name is one, too.
All setters are methods. Fixed.

2024-11-28 10:30 UTC, simongiegerich requested changes

2024-11-28 10:30 UTC, simongiegerich commented on tuda_workspace_scripts/robots.py
> +                    return f"ssh {self.user}@{self.hostname}"
**optional**: could be simplified to:
```py
if command_name in {"ssh-copy-id", "ssh"}:
    return f"{command_name} {self.user}@{self.hostname}"
```

2024-12-03 12:53 UTC, simongiegerich commented
LGTM

2024-12-03 12:53 UTC, simongiegerich approved these changes

2024-12-03 13:17 UTC, merged