Added update command
tu-darmstadt-ros-pkg/tuda_workspace_scripts pull request #5
Opened 2024-12-30 15:55 UTC by StefanFabian

Using hooks with initial hooks for system packages and git repos in workspace.

2025-01-02 10:27 UTC, Martin-Oehler requested changes
I tested the script and it did not work for me. On the console I get
```
$ hector update 
>>> Update system packages
[sudo] password for martin: 
```
When I try to enter my password, it is written in plain text to the terminal and I cannot confirm the password prompt by pressing enter.

2025-01-02 10:27 UTC, Martin-Oehler commented on scripts/hooks/update/10.system-packages.py
> +    upgrade = launch_subprocess(["sudo", "apt", "upgrade", "-y"])
This line seems to unconditionally update all of the users packages and suppress confirmation. This might be unexpected for users since `hector update`  implies that only hector software is updated. It could have unwanted side-effects.

2025-01-02 10:30 UTC, Martin-Oehler commented
Compared to the old update script, the behavior seems to have changed so repository branches are no longer changed to the default ones. I think, being able to do so would still be useful to get back to a consistent workspace state. What do you think about an additional separate script/command that changes all source repositories back to the default ones, e.g. `hector restore-default-branches` or similar?

2025-01-02 10:40 UTC, StefanFabian commented
This script simply updates the repositories. It doesn't even have the information necessary to reset branches and frankly this was not a good design decision in the old update method.
Switching a branch is a conscious choice and a simple update should not make changes to that state.

I think a restore command would unnecessarily bloat the command list, this should be part of the install if we want to have such a command again but I find the use of that very limited as well. It doesn't really add anything to the direct use of rosinstalls and I find this abstraction unnecessary.

2025-01-02 10:42 UTC, StefanFabian commented on scripts/hooks/update/10.system-packages.py
> +    upgrade = launch_subprocess(["sudo", "apt", "upgrade", "-y"])
Hm, yes, good point. I was assuming updating everything is simpler and usually a good idea but in some edge cases this might not be wanted.

2025-01-02 16:57 UTC, StefanFabian commented
> I tested the script and it did not work for me. On the console I get
> 
> ```
> $ hector update 
> >>> Update system packages
> [sudo] password for martin: 
> ```
> 
> When I try to enter my password, it is written in plain text to the terminal and I cannot confirm the password prompt by pressing enter.

Didn't notice that because my fingerprint worked but should be fixed now.
I have moved it into two separate hooks.
Here, we only update ros packages and in our overlay we will update hector packages.

2025-01-03 10:05 UTC, Martin-Oehler requested changes
I just get an error
```
$ hector update 
Traceback (most recent call last):
  File "/home/martin/projects/hector_ws/install/tuda_workspace_scripts/share/tuda_workspace_scripts/scripts/update.py", line 78, in <module>
    result = main(
             ^^^^^
  File "/home/martin/projects/hector_ws/install/tuda_workspace_scripts/share/tuda_workspace_scripts/scripts/update.py", line 37, in main
    success &= update(no_sudo=no_sudo, default_yes=default_yes)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: update() got an unexpected keyword argument 'no_sudo'
```

2025-01-03 11:39 UTC, StefanFabian commented
Try `hector build --this --clean`. I suspect you still have one of the old hook files.

2025-01-03 11:49 UTC, Martin-Oehler approved these changes

2025-01-03 11:52 UTC, merged